import { integer, timestamp, uuid } from 'drizzle-orm/pg-core';
import { uuidv7 } from '../../lib/uuid';

/** UUIDv7 primary key generated by the app; gen_random_uuid() covers manual SQL inserts. */
export const id = () => uuid('id').primaryKey().defaultRandom().$defaultFn(uuidv7);

export const createdAt = () =>
  timestamp('created_at', { withTimezone: true }).notNull().defaultNow();

export const updatedAt = () =>
  timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

/** Soft delete: rows stay for history/analytics; queries filter `deleted_at IS NULL`. */
export const deletedAt = () => timestamp('deleted_at', { withTimezone: true });

export const timestamps = () => ({ createdAt: createdAt(), updatedAt: updatedAt() });

/** Sort order inside a parent (world in course, lesson in world, ...). */
export const position = () => integer('position').notNull().default(0);
